"""Records the execution environment of the experiment into ENVIRONMENT.md.

Run this on the machine that executed run_experiment.py, with Ollama serving
the two models, so that the exact weights behind the tags qwen3.5:4b and
llama3.2:3b are pinned by digest and not only by tag:

    python env_report.py

The reviewers of the paper asked for the exact model versions; the tag alone
is mutable, the manifest digest is not.
"""
import platform
import subprocess
import sys
from datetime import date

MODELS = ["qwen3.5:4b", "llama3.2:3b"]


def model_rows():
    """(tag, digest, parameter size, quantization) for each model of interest."""
    import ollama

    found = {}
    for m in ollama.list().models:
        found[m.model] = m
    rows = []
    for tag in MODELS:
        m = found.get(tag)
        if m is None:
            rows.append((tag, "NOT FOUND on this host", "", ""))
            continue
        d = m.details
        rows.append((tag, m.digest,
                     getattr(d, "parameter_size", "") or "",
                     getattr(d, "quantization_level", "") or ""))
    return rows


def run(cmd):
    try:
        return subprocess.run(cmd, capture_output=True, text=True,
                              timeout=30).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return "unavailable"


def main():
    try:
        rows = model_rows()
        note = ""
    except Exception as exc:  # ollama absent or server down
        rows = [(t, f"unavailable ({exc.__class__.__name__})", "", "")
                for t in MODELS]
        note = ("\n> **Warning:** the model digests could not be read. Run this "
                "script again on the host that executed the experiment, with "
                "`ollama serve` running.\n")

    lines = [
        "# Execution environment",
        "",
        f"Generated by `env_report.py` on {date.today().isoformat()}.",
        note,
        "## Models",
        "",
        "| Tag | Manifest digest | Parameters | Quantization |",
        "|---|---|---|---|",
    ]
    for tag, digest, params, quant in rows:
        lines.append(f"| `{tag}` | `{digest}` | {params} | {quant} |")

    lines += [
        "",
        "## Decoding parameters",
        "",
        "| Parameter | Value |",
        "|---|---|",
        "| temperature | 0.7 |",
        "| seed | repetition index (0 to 4) |",
        "| repetitions per case | 5 |",
        "| tool exposure | function schema (`tools.json`), never inlined in the prompt |",
        "",
        "## Runtime",
        "",
        "```",
        f"ollama server : {run(['ollama', '--version'])}",
        f"python        : {sys.version.splitlines()[0]}",
        f"platform      : {platform.platform()}",
        "```",
        "",
        "## Python packages",
        "",
        "```",
        run([sys.executable, "-m", "pip", "freeze"]),
        "```",
        "",
    ]
    with open("ENVIRONMENT.md", "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print("ENVIRONMENT.md written.")
    for tag, digest, _, _ in rows:
        print(f"  {tag}: {digest}")


if __name__ == "__main__":
    main()
